Ruby on Rails/media_manager/config/routes.rb
Rails.application.routes.draw do

  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  root 'welcome#index'

  resources :users
  resources :photos
  resources :media
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

Ruby on Rails/media_manager/app/models/medium.rb
class Medium < ActiveRecord::Base
  validates :title, presence: true
  validates :content, presence: true

  belongs_to :user

  scope :by_user, ->(user_id) { where(user_id: user_id) }
  scope :search_by, ->(search) { where( "title LIKE ? ", "%#{search}%")}

end

Ruby on Rails/media_manager/app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "50x50>" },
                    :url  => "/assets/photos/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/photos/:id/:style/:basename.:extension"

  validates_attachment_presence :photo

  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
  validates :title, presence: true

  belongs_to :user
  scope :by_user, ->(user_id) { where(user_id: user_id) }
  scope :search_by, ->(search) { where( "title LIKE ? ", "%#{search}%")}

end

Ruby on Rails/media_manager/app/models/user.rb
class User < ActiveRecord::Base

  validates :name,  presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, length: { minimum: 6 }

  has_many :media
  has_many :photos
end

Ruby on Rails/media_manager/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

end

Ruby on Rails/media_manager/app/controllers/media_controller.rb
class MediaController < ApplicationController
  before_action :logged_in_user
  before_filter :find_params, only: [:show, :edit, :update, :destroy]

  def index
    if params[:search]
      @media = Medium.by_user(current_user.id).search_by(params[:search])
      @photos = Photo.by_user(current_user.id).search_by(params[:search])
    else
      @media = Medium.by_user(current_user.id)
      @photos = Photo.by_user(current_user.id)
    end
  end

  def new
    @medium = Medium.new
  end

  def create
    @medium = Medium.new(media_params)
    @medium.user_id = current_user.id
    if @medium.save
      redirect_to @medium
    else
      redirect_to media_path, alert: 'something went wrong'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @medium.update(media_params)
      redirect_to @medium
    else
      render 'edit'
    end
  end

  def destroy
    @medium.destroy

    redirect_to media_path
  end

  private

  def media_params
    params[:medium].permit(:title, :content)
  end

  def logged_in_user
    unless logged_in?
      redirect_to login_url
    end
  end

  def find_params
    @medium = Medium.find(params[:id])
  end
end

Ruby on Rails/media_manager/app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :logged_in_user

  def index
    @photos = Photo.by_user(current_user.id)
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.user_id = current_user.id
    if @photo.save
      redirect_to @photo
    else
      flash.now[:alert] = "something went wrong!"
      render 'new'
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

  private

  def photo_params
    params[:photo].permit(:title,:photo)
  end

  def logged_in_user
    unless logged_in?
      redirect_to login_url
    end
  end
end

Ruby on Rails/media_manager/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      redirect_to login_path, alert: 'Invalid email/password combination'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

Ruby on Rails/media_manager/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params[:user].permit(:name, :email, :password, :password_confirmation)
  end
end

Ruby on Rails/media_manager/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

Ruby on Rails/media_manager/app/helpers/application_helper.rb
module ApplicationHelper
end

Ruby on Rails/media_manager/app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

Ruby on Rails/media_manager/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mediamanager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="fb-root"></div>
<!-- <script src="https://apis.google.com/js/platform.js" async defer></script> -->
<div class="container-full mediaheader">
  <div class="row mediatitle"><h4 class='vcenter'>Media Manager</h4></div>
  <div class="row navlink">
    <%= link_to  'Home', root_url %>
    <% if logged_in? %>
      <%= link_to "My Media", media_path %>
      <%= link_to "Log out", logout_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up now!", signup_path %>
      <%= link_to "Log in", login_path %>
    <% end %>
  </div>
</div>
<%= yield %>

</body>
</html>

Ruby on Rails/media_manager/app/views/media/_form.html.erb
<%= form_for @medium do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :Link %>
    <%= f.text_field :content, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Submit", class: "btn newbutton btn-lg" %>
  </div>
<% end %>

Ruby on Rails/media_manager/app/views/media/edit.html.erb
<div class="container">
  <div class="row col-md-6">
    <h1>Edit Media</h1>
    <%= render 'form' %>
  </div>
</div>

Ruby on Rails/media_manager/app/views/media/index.html.erb
<div class="container">
  <div class="col-md-8">
    <div class='row searchform'>
      <%= form_tag media_path, :method => 'get' do %>
        <div class="input-group">
          <%= text_field_tag 'search', params['search'], class: 'form-control', placeholder: 'Search for...' %>
          <span class="input-group-btn">
             <%= submit_tag 'search', name:nil, class: 'btn btn-default' %>
          </span>
        </div>
      <% end %>
    </div>
    <div class="row">
      <% if flash[:alert] %>
        <div class="alert alert-danger"><%= flash[:alert] %></div>
      <% end %>
    </div>
    <div class="row gridtitle"><h4>Media List</h4></div>
    <div class="row">
      <div class="col-md-8"><b>Title</b></div>
      <div class='col-md-2'></div>
      <div class='col-md-2'></div>
    </div>
    <% @media.each do |m| %>
    <div class="row" >
      <div class='col-md-8 griddata'><%= link_to m.title, medium_path(m) %></div>
      <div class='col-md-2 griddata'><%= link_to 'Edit',edit_medium_path(m) %></div>
      <div class='col-md-2 griddata'>
        <b><%= link_to 'Delete', medium_path(m),method: :delete,data: { confirm: 'Are you sure?' }%></b>
      </div>
    </div>
    <% end %>
    <%= render :file => 'photos/index' %>
  </div>
  <div class="col-md-4">
    <div class="row"><h4 style="margin-left: 20px;">Add New Data</h4></div>
    <%= link_to 'New Media', new_medium_path, class: 'btn newbutton btn-lg' %>
    <%= link_to 'New Photo', new_photo_path, class: 'btn newbutton btn-lg' %>
  </div>
</div>

Ruby on Rails/media_manager/app/views/media/new.html.erb
<div class="container">
  <div class="row col-md-6">
    <h1>Upload Media</h1>
    <%= render 'form' %>
  </div>
</div>

Ruby on Rails/media_manager/app/views/media/show.html.erb
<div class="container">
  <div class="row">
    <h1>Media Detail</h1>
    <div class="col-md-3">
      <strong>Title:</strong>
    </div>
    <div class="col-md-6">
      <%= @medium.title %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <strong>Link:</strong>
    </div>
    <div class="col-md-6">
      <%= link_to @medium.content, @medium.content, :target => "_blank" %>
    </div>
  </div>
  <div class="row">
      <%= render  'shared/social_buttons' %>
  </div>
</div>

Ruby on Rails/media_manager/app/views/photos/index.html.erb
<div class="row gridtitle"><h4>Photos List</h4></div>
<div class="row">
  <div class="col-md-3"><b>Title</b></div>
  <div class='col-md-9'><b>Link</b></div>
</div>
<div class="row" >
<% @photos.each do |p| %>
  <div class="col-md-3 griddata"><%= p.title %></div>
  <div class='col-md-9 griddata'><%= link_to image_tag(p.photo.url(:thumb)),url_for({controller: "photos", action: 'show', id: p}) %></div>
<% end %>
</div>

Ruby on Rails/media_manager/app/views/photos/new.html.erb
<div class="container">
  <div class="row col-md-6">
        <div class="row">
    <% if flash[:alert] %>
      <div class="alert alert-danger"><%= flash[:alert] %></div>
    <% end %>
  </div>
    <h1>Upload Photo</h1>
    <%= form_for @photo, url: photos_path, :html => { :multipart => true } do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :photo %>
      <%= f.file_field :photo, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit "Upload", class: "btn newbutton btn-lg" %>
    </div>
  </div>
    <% end %>
  </div>
</div>

Ruby on Rails/media_manager/app/views/photos/show.html.erb
<div class="container">
  <div class="row">
    <h1>Photo Detail</h1>
    <div class="col-md-3">
      <strong>Title:</strong>
    </div>
    <div class="col-md-6">
      <%= @photo.title %>
    </div>
    </div>
  <div class="row">
    <div class="col-md-3">
      <strong>Photo:</strong>
    </div>
    <div class="col-md-6">
      <%= image_tag @photo.photo.url(:medium) %>
    </div>
  </div>
</div>

Ruby on Rails/media_manager/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

Ruby on Rails/media_manager/app/views/shared/_social_buttons.html.erb
<div class="col-md-9 social_button">
  <div class="col-md-5"></div>
  <%= social_share_button_tag(@medium.title, :url => @medium.content) %>
</div>

Ruby on Rails/media_manager/app/views/users/new.html.erb
<div class="container">
  <div class="row col-md-6">
    <h1>Sign up</h1>
    <%= render 'shared/error_messages' %>
    <%= form_for(@user) do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation%>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit "Sign up", class: "btn newbutton btn-lg"  %>
    </div>
    <% end %>
    <p>Registered user? <%= link_to "Log in", login_path %></p>
  </div>
</div>

Ruby on Rails/media_manager/app/views/users/show.html.erb
<div class="container">
  <div class="row col-md-6">
    <h1>Profile Page</h1>
   <h5>Welcome <%= @user.name %></h5>
  </div>
</div>

Ruby on Rails/media_manager/app/views/welcome/index.html.erb
<div class="container"><h4>Welcome, Have fun!</h4></div>